Allow installation of neovim for all users
tricktux/choco-neovim pull request #15
Opened 2021-01-15 13:43 UTC by jantari

Added a package parameter to add the neovim path for ALL users (machine PATH) instead of just the current one.

This is needed to allow a proper "installation" of neovim, so that it is accessible for all users on a computer.

2021-01-15 14:14 UTC, jantari commented
I packed the package with these changes and tried it out, works as expected

2021-01-15 19:08 UTC, tricktux commented
Thanks for the pull request!

I would like to suggest to change the option name to: **NeovimOnPathForAll**. To keep it somewhat consistent.

Also please change the `version` tag according to the [documentation][0].

[0]:https://docs.chocolatey.org/en-us/create/create-packages#package-fix-version-notation

2021-01-15 21:18 UTC, jantari commented
Thanks, I will.

Meanwhile, what do you think of the precedence between `/NoNeovimOnPath` and `/NeovimOnPathForAll` if the user were to specify both?

Should one of them override the other or should it error?

2021-01-16 02:00 UTC, tricktux commented
Great question. I think    /NoNeovimOnPath should take precedence.   
  

  

  

  
  
  
  
  
>   
> On Jan 15, 2021 at 4:18 PM, jantari  <notifications@github.com>  wrote:
>   
>   
>
> Thanks, I will.
>
>   
>
> Meanwhile, what do you think of the precedence between  /NoNeovimOnPath  and  /NeovimOnPathForAll  if the user were to specify both?
>
>   
>
> Should one of them override the other or should it error?
>
>   
>
> —
>  You are receiving this because you commented.
>  Reply to this email directly,   view it on GitHub, or   unsubscribe.
>
>

2021-01-16 22:02 UTC, jantari commented
Ok thanks, I changed that and also increased the version / package fix version with the date.

I think that should be it!

2021-01-17 03:52 UTC, tricktux requested changes
Minor logic fix

2021-01-17 03:52 UTC, tricktux commented on neovim/tools/chocolateyinstall.ps1
> +} elseif (!$pp['NeovimOnPathForAll']) {
```suggestion
} elseif ($pp['NeovimOnPathForAll']) {
```

2021-01-17 03:52 UTC, tricktux commented on neovim-git/tools/chocolateyinstall.ps1
> +} elseif (!$pp['NeovimOnPathForAll']) {
```suggestion
} elseif ($pp['NeovimOnPathForAll']) {
```

2021-01-17 17:56 UTC, jantari commented
Oof, embarassing mistake - thanks for catching it 😅

2021-01-17 20:57 UTC, tricktux commented
@jantari Absolutely nothing embarrassing about it.

Thanks for the PR!

2021-01-17 20:59 UTC, merged